// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwQHcuAjZrDBl8cURMUMdZqBJf1FapyHE',
    appId: '1:240603065720:web:1671a5eead13d07ccd2c8d',
    messagingSenderId: '240603065720',
    projectId: 'getx-auth-870dd',
    authDomain: 'getx-auth-870dd.firebaseapp.com',
    storageBucket: 'getx-auth-870dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFWB9qCRdNszrHeYiF0If9F_PPuP6KIo',
    appId: '1:240603065720:android:bfa2d7249a090d63cd2c8d',
    messagingSenderId: '240603065720',
    projectId: 'getx-auth-870dd',
    storageBucket: 'getx-auth-870dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8pOkbZzbYfWJf8Ou6O2u7gyZL_LkYfyo',
    appId: '1:240603065720:ios:71a91083a7470530cd2c8d',
    messagingSenderId: '240603065720',
    projectId: 'getx-auth-870dd',
    storageBucket: 'getx-auth-870dd.appspot.com',
    androidClientId: '240603065720-23shclu5imv4q8poq9tsgkv9v5hbh0hn.apps.googleusercontent.com',
    iosClientId: '240603065720-6j0c9js2qpnemhkd8bisrn38himr21gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireGet',
  );
}
